### ISSUE TITLE
error: Cannot read properties of undefined (reading 'bind')

### ISSUE THREAD

**Issue by xditya** [grammyjs/conversations#54]
Logs: 
```
Error in middleware while handling update 8328xxxxx TypeError: Cannot read properties of undefined (reading 'bind')
    at https://deno.land/x/grammy_conversations@v1.0.2/conversation.ts:561:65
    at Array.forEach (<anonymous>)
    at ConversationHandle._replayWait (https://deno.land/x/grammy_conversations@v1.0.2/conversation.ts:561:11)
    at run (https://deno.land/x/grammy_conversations@v1.0.2/conversation.ts:262:39)
    at runUntilComplete (https://deno.land/x/grammy_conversations@v1.0.2/conversation.ts:362:32)
    at https://deno.land/x/grammy_conversations@v1.0.2/conversation.ts:404:32
    at async https://deno.land/x/grammy@v1.11.1/composer.ts:144:13
    at async https://deno.land/x/grammy_conversations@v1.0.2/conversation.ts:317:9
    at async https://deno.land/x/grammy@v1.11.1/composer.ts:144:13
    at async https://deno.land/x/grammy@v1.11.1/convenience/session.ts:211:9
```

Minimal code which produces the above-mentioned issue: https://paste.xditya.me/CSkfRt

I'm using both i18n and conversations, storing data of both in sessions. I suppose that is the cause of this error, as it was running flawlessly until I started using i18n with sessions.
In the above code, I'm using grammY's `freeStorage` to store the sessions.

**Comment by KnorpelSenf** [comment]
Can you review #55?
